name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to trigger manual jobs
        required: false
        default: ''
jobs:
  module-02-main:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ./.p
            ./.docker
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/module-02-main/*.py') }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python $GITHUB_WORKSPACE/module-02-main/src
  module-03-user-cli-input:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ./.p
            ./.docker
            !~/.m2/repository/io/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/module-02-main/*.py') }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # cache: 'pip' # caching pip dependencies
      - run: echo 'Max' | python module-03-user-cli-input/src
